mediafeed/channels/urls.py
from django.urls import path

from channels import views

app_name = "channels"
urlpatterns = [
    path("<username>/", views.user_details, name="user_details"),
    path("<username>/<slug>/", views.category_details, name="category_details"),
    path("channel/", views.add_channel, name="add_channel"),
]

mediafeed/core/urls.py
from django.urls import path

from core import views

app_name = "core"
urlpatterns = [
    path("profile/", views.user_profile, name="user_profile"),
]

mediafeed/mediafeed/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("auth/", include("django.contrib.auth.urls")),
    path("c/", include("channels.urls")),
    path("", include("core.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

mediafeed/channels/models.py
import json
import re
from urllib.parse import urlencode

import dateparser
import requests
import xmltodict
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from parsel import Selector

from channels.managers import VideoQuerySet
from channels.utils import get_channel_feed_url, get_channel_title


class Channel(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    feed_url = models.URLField()

    class Meta:
        verbose_name = "channel"
        verbose_name_plural = "channels"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.title:
            self.title = get_channel_title(self.url)

        if not self.feed_url:
            self.feed_url = get_channel_feed_url(self.url)

        super().save(*args, **kwargs)

    def sync_videos(self):
        response = requests.get(self.feed_url)
        channel_feed = xmltodict.parse(response.text)

        existing_videos = list(Video.objects.all().values_list("video_id", flat=True))
        latest_videos = channel_feed["feed"]["entry"]
        for entry in latest_videos:
            video_id = entry["yt:videoId"]
            if video_id not in existing_videos:
                video = Video.objects.create(
                    url=entry["link"]["@href"],
                    title=entry["title"],
                    channel=self,
                    thumbnail_image=entry["media:group"]["media:thumbnail"]["@url"],
                    published_date=dateparser.parse(entry["published"]),
                )
                Feed.objects.create(video=video, feed=json.dumps(entry))


class Video(models.Model):
    url = models.URLField()
    title = models.CharField(max_length=255)
    channel = models.ForeignKey(
        Channel,
        on_delete=models.CASCADE,
        related_name="videos",
        related_query_name="video",
    )
    video_id = models.CharField(max_length=20, unique=True)
    thumbnail_image = models.URLField()
    published_date = models.DateTimeField()

    objects = VideoQuerySet.as_manager()

    class Meta:
        verbose_name = "video"
        verbose_name_plural = "videos"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.video_id:
            match = re.search(r"\?v=(?P<video_id>.*)", self.url)
            if match:
                match_dict = match.groupdict()
                video_id = match_dict.get("video_id", "")
                self.video_id = video_id
        super().save(*args, **kwargs)


class Category(models.Model):
    title = models.CharField(max_length=255)
    slug = models.CharField(max_length=255)
    public = models.BooleanField(default=False)
    channels = models.ManyToManyField(
        Channel, related_name="category", related_query_name="categories"
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        from django.urls import reverse

        return reverse(
            "channels:category_details",
            kwargs={"username": self.user.username, "slug": self.slug},
        )


class Feed(models.Model):
    video = models.OneToOneField(Video, on_delete=models.CASCADE)
    feed = models.TextField()

mediafeed/core/models.py
from django.db import models

# Create your models here.

mediafeed/channels/views.py
from django.contrib import messages
from django.contrib.auth.models import User
from django.http import Http404
from django.shortcuts import get_object_or_404, redirect, render

from channels.models import Category, Channel, Video


def category_details(request, username, slug):
    user = get_object_or_404(User, username=username)
    if request.user.is_authenticated and user == request.user:
        selected_category = get_object_or_404(Category, slug=slug, user=user)
        categories = Category.objects.filter(user=request.user).order_by("title")
    else:
        selected_category = get_object_or_404(
            Category, slug=slug, user=user, public=True
        )
        categories = Category.objects.filter(user=user, public=True).order_by("title")

    videos_of_category = Video.objects.for_categories([selected_category])

    period = request.GET.get("period", "last_24h")
    video_by_period = {
        "all": videos_of_category.all(),
        "week": videos_of_category.last_week(),
        "last_24h": videos_of_category.last_24h(),
    }
    videos = video_by_period.get(period, []).order_by("-published_date")

    context = {
        "user": user,
        "selected_category": selected_category,
        "period": period,
        "categories": categories,
        "videos": list(videos),
    }

    return render(request, "category_details.html", context=context)


def user_details(request, username):
    user = get_object_or_404(User, username=username)
    categories = []

    if request.user == user:
        ...
    else:
        categories = Category.objects.filter(user=user, public=True).order_by("title")
        if not categories:
            raise Http404()

    videos = Video.objects.for_categories(categories)

    context = {
        "categories": categories,
        "videos": videos,
    }

    return render(request, "user_details.html", context=context)


def add_channel(request):
    if request.method == "POST":
        category_id = request.POST.get("category_id")
        current_url = request.POST.get("current_url")
        channel_url = request.POST.get("url")

        channel = Channel.objects.create(url=channel_url)
        channel.sync_videos()

        messages.success(
            request, f'Channel "{channel.title}" has been successfully added.'
        )

        category = Category.objects.get(id=category_id)
        category.channels.add(channel)

        return redirect(current_url)

mediafeed/core/views.py
from django.shortcuts import redirect


def user_profile(request):
    return redirect("/c/renne/computacao")

mediafeed/channels/templates/category_details.html
{% extends "base.html" %}

{% block content %}
<section class="title" id="title">
    <h1>{{ selected_category }}</h1>
    <div class="periods">
        <a href="?period=last_24h">Last 24h</a>
        <a href="?period=week">Last Week</a>
        <a href="?period=all">All</a>
    </div>

    <div class="categories">
        {% for category in categories %}
        <a href="{{ category.get_absolute_url }}?period={{ period }}">{{ category.title }}</a>
        {% endfor %}
    </div>


 </section>

<section class="cards" id="cards">


    <ul>
    {% for video in videos %}
        <li class="card">
            <a href="{{ video.url }}" target="_blank">
                <img src="{{ video.thumbnail_image }}" alt="{{ video.title }}" />
            </a>
            <div class="card-content">
                <a class="video-title" href="{{ video.url }}" target="_blank">{{ video.title }}</a>
                <a class="video-channel" href="{{ video.channel.url }}" target="_blank">{{ video.channel.title }}</a>
                <small class="video-date">{{ video.published_date }}</small>
            </div>
        </li>
    {% endfor %}
    </ul>
</section>

{% comment %}
<nav>
    <div class="nav-categories">
        {% for category in categories %}
        {% if category == selected_category %}
        <a class="pure-button button-category-selected"
            href="{{ category.get_absolute_url }}?period={{ period }}">{{ category.title }}</a>
        {% else %}
        <a class="pure-button button-not-selected"
            href="{{ category.get_absolute_url }}?period={{ period }}">{{ category.title }}</a>
        {% endif %}
        {% endfor %}
    </div>

    <div class="nav-periods">
        {% if request.user == user %}
        <button id="add-channel-button" class="pure-button button-add">+ Add Channel</button>
        {% endif %}

        <a class="pure-button {% if period == 'last_24h' %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=last_24h">Last 24h</a>
        <a class="pure-button {% if period == "week" %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=week">Last Week</a>
        <a class="pure-button {% if period == "all" %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=all">All</a>
    </div>

    {% if request.user == user %}
    <form action="{% url 'channels:add_channel' %}" id="add-channel-form" class="pure-form pure-g pure-u-1"
        method="POST">
        {% csrf_token %}
        <fieldset>
            <div class="pure-control-group">
                <input type="hidden" name="current_url" value="{{ request.get_full_path }}" />
                <input type="hidden" name="category_id" value="{{ selected_category.id }}" />
                <input type="text" name="url" class="pure-input-1-3" placeholder="Channel URL" />
                <button id="add-channel-button" type="submit" class="pure-button button-add">Add</button>
            </div>
        </fieldset>
    </form>
    {% endif %}
</nav>

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}

{% endcomment %}

{% endblock %}

{% block extra_js %}
<script>
    document.getElementById("add-channel-form").hidden = true;

    document.getElementById("add-channel-button").onclick = function () {
        document.getElementById("add-channel-form").hidden = false;
    }
</script>
{% endblock %}

mediafeed/channels/templates/user_details.html
{% extends "base.html" %}

{% block content %}

<nav>
    <div class="nav-categories">
        {% for category in categories %}
        <a class="pure-button button-not-selected"
            href="{{ category.get_absolute_url }}?period={{ period }}">{{ category.title }}</a>
        {% endfor %}
    </div>

    <div class="nav-periods">
        <a class="pure-button {% if period == 'last_24h' %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=last_24h">Last 24h</a>
        <a class="pure-button {% if period == "week" %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=week">Last Week</a>
        <a class="pure-button {% if period == "all" %}button-period-selected{% else %}button-not-selected{% endif %}"
            href="?period=all">All</a>
    </div>
</nav>

{% for video in videos %}

{% if forloop.counter0 == 0 or forloop.counter0|divisibleby:4 %}
<div class="pure-g">
    {% endif %}

    <div class="pure-u-1 pure-u-sm-12-24 pure-u-md-6-24">
        <div class="card">
            <a href="{{ video.url }}" target="_blank">
                <img src="{{ video.thumbnail_image }}" alt="{{ video.title }}" />
            </a>
            <div class="card-content">
                <h1><a href="{{ video.url }}" target="_blank">{{ video.title }}</a></h1>
                <h2><a href="{{ video.channel.url }}" target="_blank">{{ video.channel.title }}</a></h2>
                <h2>{{ video.published_date }}</h2>
            </div>
        </div>
    </div>
    {% if forloop.counter|divisibleby:4 %}
</div>
{% endif %}

{% endfor %}

{% endblock %}

mediafeed/core/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

    {% block extra_css %}{% endblock %}
</head>

<body>
    <header id="top-header">
        <div class="top-header--logo">
            <a href="/">MediaFeed<span>.cc</span></a>
        </div>
        <div class="top-header--links">
            {% if request.user.is_authenticated %}
            <a href="{% url 'logout' %}">Sign Out</a>
            {% else %}
            <a href="">Sign Up</a>
            <a href="{% url 'login' %}">Sign In</a>
            {% endif %}
        </div>
    </header>

    <main>
        {% block content %}{% endblock %}
    </main>

    {% block extra_js %}{% endblock %}

</body>

</html>